Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.example.events.AwsLambdaSqsFunctionHandler
      CodeUri: /Users/harrajag/Hari/Dynamic-De-dup/sample/event-processor
      Runtime: java11
      Architectures:
        - x86_64